Update API types for BetterDiscord v1.11.0 (and some other minor changes)
Zerthox/betterdiscord-types pull request #10
Opened 2024-12-18 01:59 UTC by Neodymium7

The major change here is adding the new API features from the latest BD update, including:
- `Logger` and corresponding bound variant on `BdApi`
- Types for the new exported `Components`and settings APIs
- Types for `showChangelogModal`
- Types for other new utility functions

I also fixed up a few other minor things:
- Removed some unused type declarations in `bdapi.d.ts`
- Renamed `net.ts` to `net.d.ts` to match the other files
- Added more specific types to the `AddonAPI` instances for plugins and themes
- Updated the Tooltip component to include types for props
- Updated `Tooltip` in UI with more specific types

Finally, I updated the `Webpack` typings with generics on the module fetching methods to make them a bit more restrictive.

With the previous behavior, this example's return value would be `any` (which I thought was a little too permissive to be the default given that you can't always know what a query will return), but now it would be `unknown`:

```ts
const foo = BdApi.Webpack.getModule(someFilter);
// Previously - foo: any
// Now - foo: unknown
```

You can also just revert to the previous behavior with:

```ts
const foo = BdApi.Webpack.getModule<any>(someFilter);
```

As a result, I also changed `getWithKey` to return a unique type for the key instead of a string, with an object indexed by that unique type. This way the returned module can only be indexed by a returned key, since the module is only guaranteed to have the returned key anyway. For example:

```ts
const [module, key] = BdApi.Webpack.getWithKey(someFilter);
console.log(module[key]); // No error
console.log(module.someArbitraryKey); // Error!
```

Again, you can revert to the previous behavior with something like:

```ts
const [module, key]: [any, string] = BdApi.Webpack.getWithKey(someFilter);
console.log(module[key]); // No error
console.log(module.someArbitraryKey); // No error
```

Those last few changes are pretty subjective, but I figured it would be better to default to something more restrictive and let the user of the API decide whether or not to use `any` for the returned modules. If you want me to revert those `Webpack` changes before you merge, just let me know :D

2024-12-21 17:17 UTC, Zerthox commented
New APIs and Webpack changes look good. 👍 

Not sure if the return type of `UI.createTooltip()` is considered an implementation detail, the class itself is not documented in BD docs but explicitly named as `Tooltip` rather than `object` like `AddonAPI.get()`. I think its fine to leave the details in for now.

2024-12-21 17:17 UTC, Zerthox requested changes

2024-12-21 17:17 UTC, Zerthox commented on addonapi.d.ts
> +}
Not sure if it changed by now, but the object returned by AddonAPI used to be considered an implementation detail and was not documented in the BetterDiscord API.  I am not sure if we want to type BetterDiscord internal objects.

2024-12-21 17:17 UTC, Zerthox commented on components.d.ts
> +    SettingGroup: React.FunctionComponent<SettingGroupProps>;
Are these guaranteed to be Function/Class components respectively? If not, I think its better to use a generic React Component type. Same thing goes for the Discord Tooltip props, unless BD gives stability guarantees regarding the interface I dont think it should be typed here.

2024-12-21 17:17 UTC, Zerthox commented on contextmenu.d.ts
>  }
Same thing here, are these guaranteed to be function components? If people need to do Function Component specific stuff with it, I think its better if they have to cast it.

2024-12-21 22:12 UTC, Neodymium7 commented on addonapi.d.ts
> +}
I don't believe anything's changed, I just wasn't aware of that detail :P Just went ahead and removed it!

2024-12-21 22:13 UTC, Neodymium7 commented on components.d.ts
> +    SettingGroup: React.FunctionComponent<SettingGroupProps>;
Good catch! Changed everything to just be generic component types and removed Discord implementation-dependent stuff.

2024-12-21 22:14 UTC, Neodymium7 commented on contextmenu.d.ts
>  }
Was experimenting with some stuff here before but forgot to revert those type changes as well. I reverted it back to how it was originally.

2024-12-21 22:15 UTC, Neodymium7 commented
Fixed those issues according to your comments. Let me know if there's anything else I should change or anything I missed!

2024-12-22 13:02 UTC, Zerthox approved these changes

2024-12-22 13:02 UTC, Zerthox commented
Thanks!

2024-12-22 13:02 UTC, merged